version: '3.1'
services:
  stats:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  service:
    build: ./service
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - stats
      - service-db

  service-db:
    image: postgres:14-alpine
    container_name: service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root